[package]
name = "discord-selfbot-delete-all"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest = { version = "0.12.17", features = ["blocking", "json"] }
rand = "0.9.1"
url = "2.5.4"
serde_json = "1.0.140"
dotenv = "0.15.0"
serde = { version = "1.0.219", features = ["derive"] }